library(dplyr)
library(hms)
library(lubridate)
library(mockr)
library(rlang)
library(testthat)

library(lubritime)

testthat::test_check("lubritime")

# # For development use only (comment the code after use (Ctrl + Shift + C)).
#
# cffr::cff_write()
# codemetar::write_codemeta()
# covr::codecov(token = "")
# covr::package_coverage()
# devtools::check()
# devtools::check(remote = TRUE, manual = TRUE)
# devtools::check_mac_release()
# devtools::check_win_devel()
# devtools::check_win_oldrelease()
# devtools::check_win_release()
# devtools::document()
# devtools::install()
# devtools::release()
# devtools::submit_cran()
# devtools:test()
# goodpractice::gp()
# library(vscDebugger)
# lintr::lint_package()
# pkgdown::build_article("x")
# pkgdown::build_favicons(overwrite = TRUE)
# pkgdown::build_reference()
# pkgdown::build_site()
# revdepcheck::revdep_check(num_workers = 4)
# rhub::rhub_setup()
# rutils::update_pkg_versions()
# spelling::spell_check_package()
# spelling::update_wordlist()
# tcltk::tk_choose.files()
# urlchecker::url_check()
# urlchecker::url_update()
# usethis::use_coverage()
# usethis::use_dev_version()
# usethis::use_github_action("check-standard")
# usethis::use_logo(tcltk::tk_choose.files())
# usethis::use_release_issue("#.#.#")
# usethis::use_revdep()
# usethis::use_tidy_description()
# usethis::use_version()
